# this is *.properties file.
# file encoding: ISO-8859

sonar.coverage.exclusions=tools/**/*,tests/unittests/?Mock*.hpp

sonar.sourceEncoding=UTF-8

sonar.sources=.

sonar.exclusions=build/**/*,packages/**/*,src/*/resources/**/*,**/HeaderMake/**,**/test-*,tests*-*.xml,help/**/*

sonar.python.version=3
