<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="CMakeTools">
    <CMakeExe>$(VsInstallDir)Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe</CMakeExe>
    <CMakeToolsBuildDir>$([MSBuild]::NormalizePath('$(IntDir)', '..\..\CMakeTools'))</CMakeToolsBuildDir>
    <CMakeToolsOutDir>$([MSBuild]::NormalizePath('$(OutDir)', '..\'))</CMakeToolsOutDir>
  </PropertyGroup>
  <ItemDefinitionGroup Label="CMakeTools.common">
    <ClCompile>
      <AdditionalIncludeDirectories>$(CMakeToolsBuildDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <ResourceCompile>
      <AdditionalIncludeDirectories>$(CMakeToolsBuildDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ResourceCompile>
  </ItemDefinitionGroup>
  <Target Name="MakeTestResource" Outputs="$(CMakeToolsBuildDir)resources.ja-JP.zip" BeforeTargets="ResourceCompile">
    <Exec Command="chcp 65001 >nul &amp; &quot;$(CMakeExe)&quot; --build &quot;$(CMakeToolsBuildDir)&quot; --config &quot;$(Configuration)&quot; --target &quot;test_resource_zip&quot; -- /nologo" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="AppendCMakeToolsForTestCleanTargets" BeforeTargets="CoreClean">
    <!-- Add files to @Clean just before running CoreClean. -->
    <ItemGroup>
      <Clean Include="$(CMakeToolsBuildDir)resources.ja-JP.zip" />
    </ItemGroup>
  </Target>
</Project>