<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="CompileTest">
    <CompileTestSourceDir>$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..\cmake\compiletests\'))</CompileTestSourceDir>
    <CompileTestBuildDir>$([MSBuild]::NormalizePath('$(IntDir)', '..\..\compiletests\'))</CompileTestBuildDir>
  </PropertyGroup>
  <ItemGroup>
    <CompileTestTarget Include="..\sakura_core\basis\CLaxInteger.h" />
    <CompileTestTarget Include="..\sakura_core\basis\CStrictInteger.h" />
    <CompileTestTarget Include="..\sakura_core\basis\SakuraBasis.h" />
  </ItemGroup>
  <Target Name="RunCompileTests" BeforeTargets="ClCompile" Inputs="@(CompileTestTarget)" Outputs="$(CompileTestBuildDir)CMakeCache.txt">
    <SetEnv name="BUILD_PLATFORM" value="$(Platform)" prefix="false" />
    <SetEnv name="BUILD_CONFIGURATION" value="$(Configuration)" prefix="false" />
    <SetEnv name="VisualStudioVersion" value="$(VisualStudioVersion)" prefix="false" />
    <Exec Command="chcp 65001 >nul &amp; powershell.exe -NoProfile -ExecutionPolicy Bypass -Command &quot;&amp; { &amp; '$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..\pwsh\compiletests.ps1'))' -CompileTestSourceDir '$(CompileTestSourceDir)' }&quot;" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="AppendCleanTargetsForCompileTest" BeforeTargets="CoreClean">
    <RemoveDir Directories="$(CompileTestBuildDir)" />
  </Target>
</Project>