<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="CMakeTools">
    <CMakeExe>$(VsInstallDir)Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe</CMakeExe>
    <CMakeToolsBuildDir>$([MSBuild]::NormalizePath('$(IntDir)', '..\..\CMakeTools'))</CMakeToolsBuildDir>
    <CMakeToolsOutDir>$([MSBuild]::NormalizePath('$(OutDir)', '..\'))</CMakeToolsOutDir>
  </PropertyGroup>
  <ItemDefinitionGroup Label="CMakeTools.common">
    <ClCompile>
      <AdditionalIncludeDirectories>$(CMakeToolsBuildDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <ResourceCompile>
      <AdditionalIncludeDirectories>$(CMakeToolsBuildDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ResourceCompile>
  </ItemDefinitionGroup>
  <Target Name="ConfigureCMakeTools" Outputs="$(CMakeToolsBuildDir)CMakeCache.txt">
    <SetEnv name="BUILD_PLATFORM" value="$(Platform)" prefix="false" />
    <SetEnv name="BUILD_CONFIGURATION" value="$(Configuration)" prefix="false" />
    <SetEnv name="VisualStudioVersion" value="$(VisualStudioVersion)" prefix="false" />
    <Exec Command="chcp 65001 >nul &amp; powershell.exe -NoProfile -ExecutionPolicy Bypass -Command &quot;&amp; { &amp; '$(MSBuildThisFileDirectory)..\pwsh\cmaketools.ps1' -HomePath '$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..\..\..'))' }&quot;" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="GenerateVersionHeader" Outputs="$(CMakeToolsBuildDir)version.h" DependsOnTargets="ConfigureCMakeTools" BeforeTargets="ResourceCompile;ClCompile">
    <Exec Command="chcp 65001 >nul &amp; &quot;$(CMakeExe)&quot; --build &quot;$(CMakeToolsBuildDir)&quot; --config &quot;$(Configuration)&quot; --target &quot;generate_version_header&quot; -- /nologo" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="GenerateFuncCodeDefine" Outputs="$(CMakeToolsBuildDir)Funccode_define.h" DependsOnTargets="ConfigureCMakeTools" AfterTargets="GenerateVersionHeader" BeforeTargets="ResourceCompile">
    <Exec Command="chcp 65001 >nul &amp; &quot;$(CMakeExe)&quot; --build &quot;$(CMakeToolsBuildDir)&quot; --config &quot;$(Configuration)&quot; --target &quot;generate_funccode_define&quot; -- /nologo" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="GenerateFuncCodeEnum" Outputs="$(CMakeToolsBuildDir)Funccode_enum.h" DependsOnTargets="ConfigureCMakeTools" AfterTargets="GenerateVersionHeader" BeforeTargets="ClCompile">
    <Exec Command="chcp 65001 >nul &amp; &quot;$(CMakeExe)&quot; --build &quot;$(CMakeToolsBuildDir)&quot; --config &quot;$(Configuration)&quot; --target &quot;generate_funccode_enum&quot; -- /nologo" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="ExtractBregonig" Outputs="$(CMakeToolsOutDir)$(Configuration)\bregonig.dll" Condition="'$(Platform)'=='x64' Or '$(Platform)'=='Win32'" AfterTargets="Link">
    <Exec Command="chcp 65001 >nul &amp; &quot;$(CMakeExe)&quot; --build &quot;$(CMakeToolsBuildDir)&quot; --config &quot;$(Configuration)&quot; --target &quot;extract_bregonig&quot; -- /nologo" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="ExtractCTags" Outputs="$(CMakeToolsOutDir)$(Configuration)\ctags.exe" Condition="'$(Platform)'=='x64' Or '$(Platform)'=='Win32'" AfterTargets="Link">
    <Exec Command="chcp 65001 >nul &amp; &quot;$(CMakeExe)&quot; --build &quot;$(CMakeToolsBuildDir)&quot; --config &quot;$(Configuration)&quot; --target &quot;extract_ctags&quot; -- /nologo" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="GenerateLang_en_US" Outputs="$(CMakeToolsOutDir)sakura_lang_en_US.dll" DependsOnTargets="GenerateVersionHeader;GenerateFuncCodeDefine" AfterTargets="Link">
    <Exec Command="chcp 65001 >nul &amp; &quot;$(CMakeExe)&quot; --build &quot;$(CMakeToolsBuildDir)&quot; --config &quot;$(Configuration)&quot; --target &quot;sakura_lang_en_US&quot; -- /nologo" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="GenerateLang_zh_CN" Outputs="$(CMakeToolsOutDir)sakura_lang_zh_CN.dll" DependsOnTargets="GenerateVersionHeader;GenerateFuncCodeDefine" AfterTargets="Link">
    <Exec Command="chcp 65001 >nul &amp; &quot;$(CMakeExe)&quot; --build &quot;$(CMakeToolsBuildDir)&quot; --config &quot;$(Configuration)&quot; --target &quot;sakura_lang_zh_CN&quot; -- /nologo" StdOutEncoding="UTF-8" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="AppendCMakeToolsCleanTargetsForCMakeTools" BeforeTargets="CoreClean">
    <RemoveDir Directories="$(CMakeToolsBuildDir)" />
    <!-- Add files to @Clean just before running CoreClean. -->
    <ItemGroup>
      <Clean Include="$(OutDir)sakura_lang_en_US.dll" />
      <Clean Include="$(OutDir)sakura_lang_en_US.pdb" />
      <Clean Include="$(OutDir)sakura_lang_zh_CN.dll" />
      <Clean Include="$(OutDir)sakura_lang_zh_CN.pdb" />
    </ItemGroup>
  </Target>
</Project>