name: build sakura

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.adoc'
      - '**/*.md'
      - .gitignore
      - .editorconfig
  pull_request:
    paths-ignore:
      - '**/*.adoc'
      - '**/*.md'
      - .gitignore
      - .editorconfig

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to calculate shared environment variables
  setup:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.setup-env.outputs.build-id }}

    steps:
    ## see https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 過去の履歴も含めて全て取得 (checkEncoding.py で origin/master にアクセスするため)

    - name: Setup environment variables
      id: setup-env
      run: |
        $buildId = $(.\.github\Get-BuildId.ps1 ${{ github.sha }})
        echo "build-id=$buildId" >> $env:GITHUB_OUTPUT
        "build-id is '$buildId'"

    - name: Show environment variables for debug
      run: set
      shell: cmd

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Python version check
      run: python --version

    - name: Python compile check
      run: python -m compileall -f .

    - name: Check encoding
      run: python tools/checkEncoding/checkEncoding.py

  buildBmpTools:
    needs: setup
    runs-on: windows-latest

    strategy:
      matrix:
        config: [ Debug, Release ]

    env:
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: ${{ matrix.config }}
      BUILD_ID: ${{ needs.setup.outputs.output1 }}

    steps:
    - uses: actions/checkout@v4

    ## see https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Toolbar Bitmap Split/Mux
    - name: Bitmap Split/Mux
      run: |
        "msbuild.exe tools\ToolBarTools\ToolBarTools.sln `"/p:Platform=Any CPU`" /p:Configuration=${{ env.BUILD_CONFIGURATION }} /t:Build /v:q"
        msbuild.exe tools\ToolBarTools\ToolBarTools.sln "/p:Platform=Any CPU" /p:Configuration=${{ env.BUILD_CONFIGURATION }} /t:Build /v:q

    ## see https://github.com/actions/upload-artifact
    - name: Upload BmpTools artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_CONFIGURATION }}-bmpTools"
        path: |
          tools/ToolBarTools/ToolBarImageMuxer/bin/${{ env.BUILD_CONFIGURATION }}/ToolBarImageMuxer.exe
          tools/ToolBarTools/ToolBarImageSplitter/bin/${{ env.BUILD_CONFIGURATION }}/ToolBarImageSplitter.exe

  doxygen:
    needs: setup
    runs-on: windows-latest

    strategy:
      matrix:
        config: [ Debug, Release ]

    env:
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: ${{ matrix.config }}
      BUILD_ID: ${{ needs.setup.outputs.output1 }}

    steps:
    - uses: actions/checkout@v4

    - name: Install doxygen
      run: choco install doxygen.install -y

    - name: Run doxygen
      run: .\tools\doxygen\run-doxygen.bat ${{ env.BUILD_PLATFORM }} ${{ env.BUILD_CONFIGURATION }}
      shell: cmd

    - name: Upload doxygen artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_CONFIGURATION }}-doxygen"
        path: |
          html\sakura-doxygen.chm
          html\sakura-doxygen.chi
          doxygen-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}.log

  buildChm:
    needs: setup
    runs-on: windows-latest

    env:
      BUILD_ID: ${{ needs.setup.outputs.output1 }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Locale Emulator
      run: |
        $LEExpandDir = "${{ github.workspace }}\tools\LocaleEmulator"
        .\tools\LocaleEmulator\Fetch-LocaleEmulator.ps1 "${LEExpandDir}"
        echo "${LEExpandDir}" >> $env:GITHUB_PATH

    - uses: microsoft/setup-msbuild@v2

    - name: Build HTML Help
      run: build-chm.bat
      shell: cmd

    - name: Upload Compiled HTML Help artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-chm"
        path: |
          help\*\*.chm
          help\*\Compile.log
  
  buildSakura:
    needs: setup
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [ x64, ARM64, Win32 ]
        config: [ Debug, Release ]

    env:
      BUILD_PLATFORM: ${{ matrix.platform }}
      BUILD_CONFIGURATION: ${{ matrix.config }}
      BUILD_ID: ${{ needs.setup.outputs.output1 }}
      LC_ALL: ja_JP.UTF-8
      OUTPUT_DIRECTORY: ${{ github.workspace }}\${{ matrix.platform }}\${{ matrix.config }}
      VCPKG_HOST_TRIPLET: x64-windows
      SONAR_QUBE: ('x64' == ${{ matrix.platform }} || 'Debug' == ${{ matrix.config }}) && 'Yes' || ''
      IS_ALPHA: ${{ contains(fromJSON('["x64","ARM64"]'), matrix.platform) && '-alpha' || '' }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Run vcpkg bootstrap
      run: |
        .\tools\vcpkg\bootstrap-vcpkg.bat
        
    - name: Setup SonarQube environment variables
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN
      run: |
        if ('x64' -eq '${{ env.BUILD_PLATFORM }}' -and 'Debug' -eq '${{ env.BUILD_CONFIGURATION }}') {
          $projectKey = $('${{ github.repository }}' -replace '/', '_')
          echo "SONAR_PROJECT_KEY=$projectKey" >> $env:GITHUB_ENV
        }

    - uses: microsoft/setup-msbuild@v2

    - name: Install Build Wrapper
      uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

    - name: Build SakuraEditor
      run: |
        .\tools\SonarQube\Build-Project.ps1 ${{ env.BUILD_PLATFORM }} ${{ env.BUILD_CONFIGURATION }}

    - name: Upload Generated Assemblies
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}-asm"
        path: |
          build\${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\sakura_core\*.asm

    - name: Download Compiled HTML Help artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-chm"
        path: help\
    - run: |
        Copy-Item -Path help\macro\macro.chm   -Destination ${{ env.OUTPUT_DIRECTORY }}\
        Copy-Item -Path help\plugin\plugin.chm -Destination ${{ env.OUTPUT_DIRECTORY }}\
        Copy-Item -Path help\sakura\sakura.chm -Destination ${{ env.OUTPUT_DIRECTORY }}\

    - name: Prepare Exe artifacts
      run: |
        Copy-Item -Path LICENSE -Destination ${{ env.OUTPUT_DIRECTORY }}\license
        if ('-alpha' -eq '${{ env.IS_ALPHA }}') {
          Copy-Item -Path installer\warning-alpha.txt -Destination ${{ env.OUTPUT_DIRECTORY }}\
        }
        Copy-Item -Path installer\warning.txt -Destination ${{ env.OUTPUT_DIRECTORY }}\

    - name: Upload Exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_PLATFORM }}${{ env.IS_ALPHA }}-${{ env.BUILD_CONFIGURATION }}-exe"
        path: |
          ${{ env.OUTPUT_DIRECTORY }}\*.exe
          ${{ env.OUTPUT_DIRECTORY }}\*.dll
          ${{ env.OUTPUT_DIRECTORY }}\license\
          ${{ env.OUTPUT_DIRECTORY }}\*.txt
          ${{ env.OUTPUT_DIRECTORY }}\*.chm
          !${{ env.OUTPUT_DIRECTORY }}\tests1.exe

    ## see https://github.com/actions/setup-dotnet
    - name: Setup .NET (for dotnet tools)
      uses: actions/setup-dotnet@v4
    - run: dotnet tool install --global trx2junit

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Setup Node.js
      if: env.SONAR_QUBE == 'Yes'
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install OpenCppCoverage
      run: |
        choco install OpenCppCoverage -y

    - name: Run Tests
      if: env.BUILD_PLATFORM != 'ARM64' # ARM64モジュールは実行できない
      run: |
        $testCommand = "${{ env.OUTPUT_DIRECTORY }}\tests1.exe"
        $testName = $([System.IO.Path]::GetFileNameWithoutExtension($testCommand))
        & "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe" `
          --export_type cobertura:${{ github.workspace }}\$testName-coverage.xml `
          --modules $testCommand `
          --sources "${{ github.workspace }}" `
          --excluded_sources "${{ github.workspace }}\build" `
          --working_dir $([System.IO.Path]::GetDirectoryName($testCommand)) `
          --cover_children `
          -- `
          $testCommand `
          --gtest_output=xml:${{ github.workspace }}\$testName-googletest.xml

    - name: Upload test result
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: env.SONAR_QUBE == 'Yes'
      with:
        files: |
          *-googletest.xml

    - name: Download doxygen artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_CONFIGURATION }}-doxygen"
    - run: |
        Copy-Item -Path html\sakura-doxygen.chm -Destination ${{ env.OUTPUT_DIRECTORY }}\
        Copy-Item -Path html\sakura-doxygen.chi -Destination ${{ env.OUTPUT_DIRECTORY }}\

    - name: Upload Dev artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}-dev"
        path: |
          ${{ env.OUTPUT_DIRECTORY }}\*.exe
          ${{ env.OUTPUT_DIRECTORY }}\*.dll
          ${{ env.OUTPUT_DIRECTORY }}\*.pdb
          ${{ env.OUTPUT_DIRECTORY }}\license\
          ${{ env.OUTPUT_DIRECTORY }}\*.txt
          ${{ env.OUTPUT_DIRECTORY }}\*.chm
          ${{ env.OUTPUT_DIRECTORY }}\*.chi

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN && env.SONAR_QUBE == 'Yes'
      with:
        args: >
          -D"sonar.organization=${{ github.repository_owner }}"
          -D"sonar.projectKey=${{ env.SONAR_PROJECT_KEY }}"
          -D"sonar.host.url=https://sonarcloud.io"
          -D"sonar.cfamily.compile-commands=build/${{ env.BUILD_PLATFORM }}/${{ env.BUILD_CONFIGURATION }}/bw-output/compile_commands.json"
          -D"sonar.cfamily.cppunit.reportPath=*-googletest.xml"
          -D"sonar.cfamily.cobertura.reportPaths=tests1-coverage.xml"

    - name: Upload Log artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}-log"
        path: |
          msbuild-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}.log
          doxygen-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}.log
          help\*\Compile.log

  mingw:
    needs: setup
    runs-on: windows-latest

    strategy:
      matrix:
        msystem: [ MINGW64, UCRT64 ]
        config: [ Debug, Release ]

    env:
      BUILD_PLATFORM: MinGW
      BUILD_CONFIGURATION: ${{ matrix.config }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run vcpkg bootstrap
      run: |
        .\tools\vcpkg\bootstrap-vcpkg.bat
      shell: pwsh

    - name: Set up MSYS2
      id: msys2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
        msystem: ${{ matrix.msystem }}
        update: true

    - name: Show gcc version
      env:
        MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
      run: |
        echo "$env:MSYS2_LOCATION"
        gcc --version

    - name: Configure CMake project
      run: |
        cmake --preset msys2

    - name: Build with MinGW-w64-gcc
      run: cmake --build --preset msys2

    - name: Run unit tests
      run: ctest --preset msys2

  buildInstaller:
    needs: [ setup, doxygen, buildChm, buildSakura ]
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [ x64, Win32 ]

    env:
      BUILD_ID: ${{ needs.setup.outputs.output1 }}
      BUILD_PLATFORM: ${{ matrix.platform }}
      BUILD_CONFIGURATION: Release
      OUTPUT_DIRECTORY: ${{ github.workspace }}\${{ matrix.platform }}\Release
      IS_ALPHA: ${{ contains(fromJSON('["x64","ARM64"]'), matrix.platform) && '-alpha' || '' }}

    steps:
    - uses: actions/checkout@v4

    - name: Download doxygen artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_CONFIGURATION }}-doxygen"

    - name: Download Compiled HTML Help artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-chm"
        path: help\

    - name: Download Exe artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_PLATFORM }}${{ env.IS_ALPHA }}-${{ env.BUILD_CONFIGURATION }}-exe"
        path: ${{ env.OUTPUT_DIRECTORY }}\

    - name: Download Log artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}-log"

    - name: Update/Install Inno Setup
      run: choco upgrade innosetup --confirm

    - name: Build installer with Inno Setup
      run: build-installer.bat ${{ env.BUILD_PLATFORM }} ${{ env.BUILD_CONFIGURATION }}
      shell: cmd

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-${{ env.BUILD_PLATFORM }}${{ env.IS_ALPHA }}-installer"
        path: |
          installer\Output-${{ env.BUILD_PLATFORM }}\*.exe
          installer\Output-${{ env.BUILD_PLATFORM }}\warning-alpha.txt
          installer\Output-${{ env.BUILD_PLATFORM }}\warning.txt
