name: build sakura

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
  pull_request:
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to calculate shared environment variables
  setup:
    runs-on: windows-latest

    steps:
    ## see https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 過去の履歴も含めて全て取得 (checkEncoding.py で origin/master にアクセスするため)

    - name: Setup environment variables
      run: |
        $buildId = $(.\.github\Get-BuildId.ps1 ${{ github.sha }})
        echo "BUILD_ID=$buildId" >> $env:GITHUB_ENV
        "BUILD_ID is '$buildId'"

    - name: Show environment variables for debug
      run: set
      shell: cmd

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Python version check
      run: python --version

    - name: Python compile check
      run: python -m compileall -f .

    - name: Check encoding
      run: python tools/checkEncoding/checkEncoding.py

  buildBmpTools:
    needs: setup
    runs-on: windows-latest

    strategy:
      matrix:
        config: [ Debug, Release ]

    env:
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: ${{ matrix.config }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment variables
      run: |
        $buildId = $(.\.github\Get-BuildId.ps1 ${{ github.sha }})
        echo "BUILD_ID=$buildId" >> $env:GITHUB_ENV
        "BUILD_ID is '$buildId'"

    ## see https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Toolbar Bitmap Split/Mux
    - name: Bitmap Split/Mux
      run: |
        "msbuild.exe tools\ToolBarTools\ToolBarTools.sln `"/p:Platform=Any CPU`" /p:Configuration=${{ env.BUILD_CONFIGURATION }} /t:Build /v:q"
        msbuild.exe tools\ToolBarTools\ToolBarTools.sln "/p:Platform=Any CPU" /p:Configuration=${{ env.BUILD_CONFIGURATION }} /t:Build /v:q

    ## see https://github.com/actions/upload-artifact
    - name: Upload BmpTools artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-bmpTools-${{ env.BUILD_CONFIGURATION }}"
        path: |
          tools/ToolBarTools/ToolBarImageMuxer/bin/${{ env.BUILD_CONFIGURATION }}/ToolBarImageMuxer.exe
          tools/ToolBarTools/ToolBarImageSplitter/bin/${{ env.BUILD_CONFIGURATION }}/ToolBarImageSplitter.exe

  doxygen:
    needs: setup
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [ x64, Win32 ]
        config: [ Debug, Release ]

    env:
      BUILD_PLATFORM: ${{ matrix.platform }}
      BUILD_CONFIGURATION: ${{ matrix.config }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment variables
      run: |
        $buildId = $(.\.github\Get-BuildId.ps1 ${{ github.sha }})
        echo "BUILD_ID=$buildId" >> $env:GITHUB_ENV

    - name: Install doxygen
      run: choco install doxygen.install -y

    - name: Run doxygen
      run: .\tools\doxygen\run-doxygen.bat ${{ env.BUILD_PLATFORM }} ${{ env.BUILD_CONFIGURATION }}
      shell: cmd

    - name: Upload doxygen artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-doxygen-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"
        path: |
          html\sakura-doxygen.chm
          html\sakura-doxygen.chi
          doxygen-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}.log

  buildChm:
    needs: setup
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment variables
      run: |
        $buildId = $(.\.github\Get-BuildId.ps1 ${{ github.sha }})
        echo "BUILD_ID=$buildId" >> $env:GITHUB_ENV

    - name: Install Locale Emulator
      run: |
        $LEExpandDir = "${{ github.workspace }}\tools\LocaleEmulator"
        .\tools\LocaleEmulator\Fetch-LocaleEmulator.ps1 "${LEExpandDir}"
        echo "${LEExpandDir}" >> $env:GITHUB_PATH

    - uses: microsoft/setup-msbuild@v2

    - name: Build HTML Help
      run: build-chm.bat
      shell: cmd

    - name: Upload Compiled HTML Help artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-chm"
        path: |
          help\*\*.chm
          help\*\Compile.log
  
  buildSakura:
    needs: setup
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [ x64, Win32 ]
        config: [ Debug, Release ]

    env:
      BUILD_PLATFORM: ${{ matrix.platform }}
      BUILD_CONFIGURATION: ${{ matrix.config }}

    steps:
    ## see https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup environment variables
      run: |
        echo "CI_ACCOUNT_NAME=${{ github.actor }}" >> $env:GITHUB_ENV
        echo "CI_REPO_NAME=${{ github.repository }}" >> $env:GITHUB_ENV
        echo "CI_BUILD_VERSION=${{ github.run_id }}" >> $env:GITHUB_ENV
        echo "CI_BUILD_NUMBER=${{ github.run_number }}" >> $env:GITHUB_ENV

        $gitUrl = "${ env:GITHUB_SERVER_URL }/${{ github.repository }}"
        echo("CI_BUILD_URL=$gitUrl/actions/runs/${{ github.run_id }}") >> $env:GITHUB_ENV
        echo("GITHUB_COMMIT_URL=$gitUrl/commit/${{ github.sha }}") >> $env:GITHUB_ENV

        if ('pull_request' -eq '${{github.event_name}}') {
          echo("GITHUB_PR_NUMBER= ${{ github.event.pull_request.number }}") >> $env:GITHUB_ENV
          echo("GITHUB_PR_HEAD_SHORT_COMMIT=${{ github.event.pull_request.head.sha }}".SubString(0, 8)) >> $env:GITHUB_ENV
          echo("GITHUB_PR_HEAD_COMMIT=${{ github.event.pull_request.head.sha }}") >> $env:GITHUB_ENV
          echo("GITHUB_PR_HEAD_URL=$gitUrl/pull/${{ github.event.pull_request.number }}/commits/${{ github.event.pull_request.head.sha }}") >> $env:GITHUB_ENV
        }

        if ('tag' -eq '${{ github.ref_type }}') {
          echo("GITHUB_TAG_NAME= ${{ github.ref_name }}") >> $env:GITHUB_ENV
        }

        if ('x64' -eq '${{ env.BUILD_PLATFORM }}') {
          echo "IS_ALPHA=-alpha" >> $env:GITHUB_ENV
        }

        if ('x64' -eq '${{ env.BUILD_PLATFORM }}' -and 'Debug' -eq '${{ env.BUILD_CONFIGURATION }}') {
          $projectKey = $('${{ github.repository }}' -replace '/', '_')
          echo "SONAR_PROJECT_KEY=$projectKey" >> $env:GITHUB_ENV
          echo "SONAR_QUBE=Yes" >> $env:GITHUB_ENV
        }

        $buildId = $(.\.github\Get-BuildId.ps1 ${{ github.sha }})
        echo "BUILD_ID=$buildId" >> $env:GITHUB_ENV

    - uses: microsoft/setup-msbuild@v2

    ## see https://github.com/actions/setup-dotnet
    - name: Setup .NET (for dotnet tools)
      uses: actions/setup-dotnet@v4

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Setup Node.js
      if: env.SONAR_QUBE == 'Yes'
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install Build Wrapper
      uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5
      
    - name: Build SakuraEditor
      run: .\tools\SonarQube\Build-Project.ps1 ${{ env.BUILD_PLATFORM }} ${{ env.BUILD_CONFIGURATION }}

    - name: Run Tests
      run: .\tools\SonarQube\Run-Tests.ps1 ${{ env.BUILD_PLATFORM }} ${{ env.BUILD_CONFIGURATION }}

    - name: Upload test result
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: env.SONAR_QUBE == 'Yes'
      with:
        files: |
          *-googletest.xml

    - name: Upload Generated Assemblies
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-asm-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"
        path: |
          build\${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\sakura_core\*.asm

    - name: Upload Exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-exe-${{ env.BUILD_PLATFORM }}${{ env.IS_ALPHA }}-${{ env.BUILD_CONFIGURATION }}"
        path: |
          ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\*.exe
          ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\*.dll

    - name: Upload Dev artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-dev-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"
        path: |
          ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\*.pdb

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        LC_ALL: ja_JP.UTF-8
      if: env.SONAR_TOKEN && env.SONAR_QUBE == 'Yes'
      with:
        args: >
          -D"sonar.organization=${{ github.repository_owner }}"
          -D"sonar.projectKey=${{ env.SONAR_PROJECT_KEY }}"
          -D"sonar.host.url=https://sonarcloud.io"
          -D"sonar.cfamily.compile-commands=build/${{ env.BUILD_PLATFORM }}/${{ env.BUILD_CONFIGURATION }}/bw-output/compile_commands.json"
          -D"sonar.cfamily.cppunit.reportPath=*-googletest.xml"
          -D"sonar.cfamily.vscoveragexml.reportsPath=TestResults/*/*.xml"

    - name: Upload Log artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-log-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"
        path: |
          msbuild-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}.log
          doxygen-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}.log
          help\*\Compile.log

  mingw:
    needs: setup
    runs-on: windows-latest

    strategy:
      matrix:
        config: [ Debug, Release ]

    env:
      BuildPlatform: MinGW
      Configuration: ${{ matrix.config }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSYS2
      id: msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make

    - run: pacman -S --noconfirm p7zip

    - env:
        MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
      run: |
        echo "$env:MSYS2_LOCATION"
        gcc --version

    - name: Build with MinGW-w64-gcc
      run: ./build-gnu.bat ${{ env.BuildPlatform }} ${{ env.Configuration }}

    - name: Run unit tests
      run: ./tests1.exe --gtest_output=xml:tests1-googletest.xml
      working-directory: ${{ env.BuildPlatform }}/${{ env.Configuration }}

  buildInstaller:
    needs: [ doxygen, buildChm, buildSakura ]
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [ x64, Win32 ]

    env:
      BUILD_PLATFORM: ${{ matrix.platform }}
      BUILD_CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment variables
      run: |
        if ('x64' -eq '${{ env.BUILD_PLATFORM }}') {
          echo "IS_ALPHA=-alpha" >> $env:GITHUB_ENV
        }
        $buildId = $(.\.github\Get-BuildId.ps1 ${{ github.sha }})
        echo "BUILD_ID=$buildId" >> $env:GITHUB_ENV


    - name: Download doxygen artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-doxygen-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"

    - name: Download Exe artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-exe-${{ env.BUILD_PLATFORM }}${{ env.IS_ALPHA }}-${{ env.BUILD_CONFIGURATION }}"
        path: ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\
    - run: |
        New-Item -Path ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\license          -ItemType Directory
        New-Item -Path ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\license\bregonig -ItemType Directory
        New-Item -Path ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\license\ctags    -ItemType Directory
        Copy-Item -Path LICENSE -Destination ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\license
        if ('x64' -eq '${{ env.BUILD_PLATFORM }}') {
          Copy-Item -Path installer\warning-alpha.txt -Destination ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\
        }
        Copy-Item -Path installer\warning.txt -Destination ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\

    - name: Download Compiled HTML Help artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-chm"
        path: help\
    - run: |
        Copy-Item -Path help\macro\macro.chm   -Destination ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\
        Copy-Item -Path help\plugin\plugin.chm -Destination ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\
        Copy-Item -Path help\sakura\sakura.chm -Destination ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\

    - name: Download Dev artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-dev-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"
        path: ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\

    - name: Download Log artifact
      uses: actions/download-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-log-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"

    - name: Update/Install Inno Setup
      run: choco upgrade innosetup --confirm

    - name: Build installer with Inno Setup
      run: build-installer.bat ${{ env.BUILD_PLATFORM }} ${{ env.BUILD_CONFIGURATION }}
      shell: cmd

    - run: |
        if ('x64' -eq '${{ env.BUILD_PLATFORM }}') {
          Copy-Item -Path installer\warning-alpha.txt -Destination installer\Output-${{ env.BUILD_PLATFORM }}\
        }
        Copy-Item -Path installer\warning.txt -Destination installer\Output-${{ env.BUILD_PLATFORM }}\

    - name: Re-Upload doxygen artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-doxygen-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"
        path: |
          html\sakura-doxygen.chm
          html\sakura-doxygen.chi
        overwrite: true

    - name: Re-Upload Exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-exe-${{ env.BUILD_PLATFORM }}${{ env.IS_ALPHA }}-${{ env.BUILD_CONFIGURATION }}"
        path: |
          ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\*.exe
          !${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\tests*.exe
          ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\*.dll
          ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\warning-alpha.txt
          ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\warning.txt
        overwrite: true

    - name: Re-Upload Compiled HTML Help artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-chm"
        path: |
          ${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}\*.chm
        overwrite: true
  
    - name: Re-Upload Log artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-log-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}"
        path: |
          help\*\Compile.log
          doxygen-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}.log
          msbuild-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}.log
        overwrite: true

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: "sakura${{ env.BUILD_ID }}-installer-${{ env.BUILD_PLATFORM }}${{ env.IS_ALPHA }}"
        path: |
          installer\Output-${{ env.BUILD_PLATFORM }}\*.exe
          installer\Output-${{ env.BUILD_PLATFORM }}\warning-alpha.txt
          installer\Output-${{ env.BUILD_PLATFORM }}\warning.txt
