name: SonarCloud

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
  pull_request_target:
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonar:
    name: Scan
    runs-on: windows-latest

    env:
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: Debug

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: '${{ github.event.pull_request.head.sha }}'
        submodules: true

    - name: Setup environment variables
      run: |
        echo "NUM_VSVERSION=$($(vswhere -latest -property catalog_productDisplayVersion) -replace '^(\d+)\..+$', '$1')" >> $env:GITHUB_ENV

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Install OpenCppCoverage with XmlExporter
      working-directory: ${{ runner.temp }}
      run: |
        choco install OpenCppCoverage -y
        Invoke-WebRequest -OutFile XmlExporter-x64.zip https://github.com/berryzplus/XmlExporter/releases/download/v1.0.0/XmlExporter-x64.zip
        7z e XmlExporter-x64.zip
        Move-Item -Path XmlExporter.dll -Destination "C:\Program Files\OpenCppCoverage\Plugins\Exporter\xml.dll"
        echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

    - name: Build SakuraEditor
      run: .\tools\Build-SakuraEditor.ps1

    - name: Run Tests
      run: .\tools\Run-Tests.ps1

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN
      with:
        args: >
          -Dsonar.organization="${{ github.repository_owner }}"
          -Dsonar.projectKey=$("${{ github.repository }}".Replace('/', '_'))
